### ISSUE TITLE
error in docker-compose up

### ISSUE THREAD

**Issue by plysytsya** [brandonrobertz/autoscrape-py#3]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /app/www/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/app/www/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-25T18_39_46_802Z-debug.log
ERROR: Service 'flask' failed to build : The command '/bin/sh -c cd /app/www && npm install && npm run download-hextractor && npm run build' returned a non-zero code: 254

**Comment by brandonrobertz** [comment]
did you get the submodules?
`git submodule init && git submodule update`
